# ------------------------ These styles apply to all wikis ------------------------
all: |
    .mw-empty-elt {
        display: none;
    }

es.wikipedia.org: |
   .mw-ref a::before { content: ''; }

zh.wikipedia.org: |
   /* Needed in the resource-modules hack scenario where
    * it appears some JS module is not hidiing this in the
    * Parsoid case unlike the core case */
   div#bluedeck_ding, div#bluedeck_ding_history {
       display: none;
   }
fr.wikipedia.org: |
   span.mw-reference-text sup {
       vertical-align: text-top;
       position: relative;
       top: -0.1em;
       font-size: 0.75em;
   }

# --- needed because gadgets aren't included before diffing ---
de.wikipedia.org: |
   a[rel="mw:referencedBy"]::before {
       font-style: italic;
   }
   span[rel="mw:referencedBy"] {
       counter-reset: mw-ref-linkback 0;
   }
   span[rel="mw:referencedBy"] > a::before {
       font-style: italic;
       content: counter(mw-ref-linkback, lower-alpha);
   }

# --- needed because gadgets aren't included before diffing ---
sv.wikipedia.org: |
   span[rel="mw:referencedBy"]::before {
       content: "^ [";
   }
   span[rel="mw:referencedBy"]::after {
       content: "]";
   }
   span[rel="mw:referencedBy"] {
       counter-reset: mw-ref-linkback 0;
   }
   span[rel="mw:referencedBy"] > a::before {
       vertical-align: middle;
       content: counter( mw-ref-linkback, lower-alpha );
   }
   .mw-ref > a[data-mw-group=not]::after {
       content: '[' counter( mw-Ref, lower-alpha ) ']';
   }
   a[rel="mw:referencedBy"]::before {
       content: "^";
   }
ar.wikipedia.org: |
   [rel="mw:referencedBy"]::before {
       content: "^ ";
   ]
